functionsDirectory = "/Users/jules/Desktop/Stop Being Alone/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
redirects = []

[build]
publish = "/Users/jules/Desktop/Stop Being Alone"
publishOrigin = "config"
functions = "/Users/jules/Desktop/Stop Being Alone/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions.max-memory]
schedule = "0 0 * * 0"

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-functions-install-core"

[plugins.inputs]

[[headers]]
for = "/js/*"

[headers.values]
Cache-Control = "public, max-age=3600"